---
abstract: 'Load config files of various types'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-ConfigLoader
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.7008
  Config::Any: 0.08
  Data::Visitor: 0.02
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.21
